# Generated by Django 3.0.8 on 2020-07-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_auto_20200715_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
